# Generated by Django 3.2.9 on 2021-11-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211122_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firedemployee',
            name='middle_name',
        ),
    ]
