# Generated by Django 3.2.9 on 2021-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_firedemployee_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='View1',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
                ('product_type', models.CharField(db_column='Product Type', max_length=50)),
            ],
            options={
                'db_table': 'view1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View2',
            fields=[
                ('product_type', models.CharField(db_column='Product Type', max_length=50, primary_key=True, serialize=False)),
                ('number_of_products', models.BigIntegerField(db_column='Number of Products')),
            ],
            options={
                'db_table': 'view2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View3',
            fields=[
                ('employee_id', models.IntegerField(db_column='Employee ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=50)),
                ('date_of_birth', models.DateField(db_column='Date of Birth')),
                ('work_place', models.IntegerField(db_column='Works in Store with id:')),
            ],
            options={
                'db_table': 'view3',
                'managed': False,
            },
        ),
    ]
