# Generated by Django 3.2.9 on 2021-11-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_view1_view2_view3'),
    ]

    operations = [
        migrations.CreateModel(
            name='View10',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View11',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View12',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view12',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View13',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view13',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View4',
            fields=[
                ('order_id', models.IntegerField(db_column='Order ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=50)),
            ],
            options={
                'db_table': 'view4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View5',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('work_place_id', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'view5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View8',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View9',
            fields=[
                ('product_id', models.IntegerField(db_column='Product ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='Product Name', max_length=50)),
                ('product_description', models.CharField(db_column='Product Description', max_length=250)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=15)),
                ('spec1_name', models.CharField(db_column='Specification 1', max_length=50)),
                ('spec1_value', models.CharField(db_column='Specification 1 Value', max_length=50)),
                ('spec2_name', models.CharField(db_column='Specification 2', max_length=50)),
                ('spec2_value', models.CharField(db_column='Specification 2 Value', max_length=50)),
                ('spec3_name', models.CharField(db_column='Specification 3', max_length=50)),
                ('spec3_value', models.CharField(db_column='Specification 3 Value', max_length=50)),
            ],
            options={
                'db_table': 'view9',
                'managed': False,
            },
        ),
    ]
